pull_request_rules:
  - name: Automatic merge on review
    conditions:
      - "#approved-reviews-by>=0"
      - base=master
      - label!=needs response
    actions:
      merge:
        method: merge
      delete_head_branch: {}

  - name: Add Label Remove Label TEST
    conditions:
      - "#approved-reviews-by=0"
    actions:
      label:
        add: ["test"]